version: '3'

services:
  basedata:
    restart: always
    image: "postgres:13-alpine"
    restart: always
    volumes:
        - ./base_data/:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    networks:
        - test_network

  back_api:
    restart: always
    build: ./user_images_service
    env_file:
        - .env
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 80
    depends_on: 
      - basedata
    networks:
      - test_network


  nginx:
    image: nginx:1.17
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    depends_on: 
      - back_api
    networks:
      - test_network
    ports:
      - "80:80"
      - "443:443"
   
 
    

networks:
  test_network:
    driver: bridge